version: "3.9"

services:

  #PHP + Apache
  php:
    container_name: php
    build:
      context: .
    ports:
      - '9000:9000'
    volumes:
      - .:/var/www
    depends_on:
      - database
 
  #Base de données
  database:
    container_name: database
    image: "mysql:5.7"
    restart: 'always'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - 3306
    expose:
      - 3306

  ###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports: [1025, 1080]