version: "3.9"

services:

  #PHP + Apache
  php:
    container_name: php
    build:
      context: .
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/app
    depends_on:
      - database
 
  #Base de données
  database:
    container_name: database
    image: "mariadb:10.3"
    restart: 'always'
    environment:
      MARIADB_ROOT_PASSWORD: "root"
      MARIADB_DATABASE: "sup_database"
      MARIADB_USER: "root"
      MARIADB_PASSWORD: "root"

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

  ###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports: [1025, 1080]